### ISSUE TITLE
Feature request: ability to set priority for CUDA streams 

### ISSUE THREAD

**Issue by srinivas212** [openucx/xccl#64]
Would it be possible to explicitly set the priority of NCCL or native CUDA streams? 

https://github.com/pytorch/pytorch/blob/0c5cd8c2b9cdf473e30bbb1b49ca80ed442813df/torch/lib/c10d/ProcessGroupNCCL.cpp#L846

**Comment by Sergei-Lebedev** [comment]
Yes, it's possible. However we still discussing how to properly expose CUDA related options in interface, adding this issue to backlog, thanks!

**Comment by Sergei-Lebedev** [comment]
Added in https://github.com/openucx/xccl/pull/97
